# Generated by Django 4.1.1 on 2022-09-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='moviesId',
            new_name='movieId',
        ),
    ]
