# Generated by Django 4.1.1 on 2022-09-17 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_moviesid_movies_movieid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
